"""Initial local setup

Revision ID: 529976b2ece7
Revises: 
Create Date: 2026-01-20 08:58:29.836596

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '529976b2ece7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_buckets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('geo_buckets', schema=None) as batch_op:
        # batch_op.create_index('idx_geo_buckets_center', ['center'], unique=False, postgresql_using='gist')

    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('bucket_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['geo_buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('properties', schema=None) as batch_op:
    #     batch_op.create_index('idx_properties_geom', ['geom'], unique=False, postgresql_using='gist')

    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # with op.batch_alter_table('properties', schema=None) as batch_op:
    #     batch_op.drop_index('idx_properties_geom', postgresql_using='gist')

    op.drop_table('properties')
    # with op.batch_alter_table('geo_buckets', schema=None) as batch_op:
    #     batch_op.drop_index('idx_geo_buckets_center', postgresql_using='gist')
    op.drop_table('geo_buckets')
    # ### end Alembic commands ###
